set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_C_COMPILER C:/mingw64/bin/gcc.exe)
set(CMAKE_CXX_COMPILER C:/mingw64/bin/g++.exe)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)